spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          client-id: 689942400875-uvg7leg3e1lad170n4otbjtrbir1qpo4.apps.googleusercontent.com
  datasourse:
    url: jdbc:derby:dungeon_run_db;create=true;collation=TERRITORY_BASED:PRIMARY
  jpa:
    database-platform: org.hibernate.dialect.DerbyTenSevenDialect
    hibernate:
      ddl-auto: update
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: ddl.sql
server:
  port: 18181
  servlet:
    context-path: /dungeonrun
